#
# ____OreGenerator____
#       Config
#

database:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: supersafe1234
  tablename: oregenerators

general:
  maximumgenerators: 2
  generatorrange: 2

# overworlds: generators produce overworld ores in those worlds
  overworlds:
  - "world"
  - "bskyblock_world"

# netherworlds: generators produce nether ores in those worlds
  netherworlds:
  - "world_nether"
  - "bskyblock_nether"