#
# ____Erzgenerator____
#       Config
#

database:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: supersafe1234
  tablename: oregenerators

general:
  maximumgenerators: 2